title: Christian Hafner
email: chafner@ist.ac.at
description: "Christian Hafner, PhD Student, Computational Fabrication, IST Austria"
baseurl: "" # the subpath of your site, e.g. /blog
domain: chrishafner.github.io
url: https://chrishafner.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chrishafner

plugins:
  - jekyll-sitemap